include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/firebase_options.dart
  language:
    strict-inference: true
    strict-raw-types: true
linter:
  rules:
    always_use_package_imports: true
