// File generated by FlutterFire CLI for the dev flavor.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        're-run FlutterFire CLI targeting the web platform.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFH0lr2xtat7g6N9Hjt7odKcS1yGSKM1M',
    appId: '1:23584005502:android:7d22b8998e3bb753bf672f',
    messagingSenderId: '23584005502',
    projectId: 'placeholder-76937',
    storageBucket: 'placeholder-76937.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQD8SwYgBtfZVOkjw7XSQ92d41aZ1PtPg',
    appId: '1:23584005502:ios:6a723129e9ccfcc2bf672f',
    messagingSenderId: '23584005502',
    projectId: 'placeholder-76937',
    storageBucket: 'placeholder-76937.firebasestorage.app',
    iosBundleId: 'com.temp.placeholder.dev',
  );
}
